packages:
  - apps/*
  - packages/*
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'
  ws@>=8.0.0 <8.21.0: '>=8.21.0'
  '@opentelemetry/propagator-jaeger@<2.9.0': '>=2.9.0'
  '@opentelemetry/core@<2.8.0': '>=2.8.0'
  fflate@>=0.8.0 <0.8.3: '>=0.8.3'
